-- oracle
SELECT DATETIME
FROM (SELECT DATETIME FROM ANIMAL_INS ORDER BY 1 DESC)
WHERE ROWNUM = 1;

-- mysql
SET @ROWNUM := 0;

SELECT B.DATETIME
FROM (SELECT @rownum:=@rownum+1 RK, A.DATETIME
        FROM (SELECT DATETIME FROM ANIMAL_INS ORDER BY 1 DESC) A) B
WHERE RK = 1;